# Based in: https://gitlab.com/AaronErhardt/crab-tag/-/blob/master/.gitlab-ci.yml

image: alpine:latest

pages:
  stage: deploy
  script:
    - ls
    - mkdir public
    - cp -r ./src public
    - cp -r index.html public
  artifacts:
    paths:
      - public
  only:
    - main
